// BOARDS------------------------------------------------------
export const FETCH_BOARDS = 'FETCH_BOARDS'
export const FETCH_BOARDS_START = 'FETCH_BOARDS_START'
export const FETCH_BOARDS_SUCCESS = 'FETCH_BOARDS_SUCCESS'
export const FETCH_BOARDS_FAIL = 'FETCH_BOARDS_FAIL'

export const CREATE_BOARD = 'CREATE_BOARD'
export const CREATE_BOARD_START = 'CREATE_BOARD_START'
export const CREATE_BOARD_SUCCESS = 'CREATE_BOARD_SUCCESS'
export const CREATE_BOARD_FAIL = 'CREATE_BOARD_FAIL'

export const DELETE_BOARD = 'DELETE_BOARD'
export const DELETE_BOARD_START = 'DELETE_BOARD_START'
export const DELETE_BOARD_SUCCESS = 'DELETE_BOARD_SUCCESS'
export const DELETE_BOARD_FAIL = 'DELETE_BOARD_FAIL'

export const UPDATE_BOARD = 'UPDATE_BOARD'
export const UPDATE_BOARD_START = 'UPDATE_BOARD_START'
export const UPDATE_BOARD_SUCCESS = 'UPDATE_BOARD_SUCCESS'
export const UPDATE_BOARD_FAIL = 'UPDATE_BOARD_FAIL'


// BOARD_RESOURCES------------------------------------------------------
export const FETCH_BOARD_RESOURCES = 'FETCH_BOARD_RESOURCES'
export const FETCH_BOARD_RESOURCES_START = 'FETCH_BOARD_RESOURCES_START'
export const FETCH_BOARD_RESOURCES_SUCCESS = 'FETCH_BOARD_RESOURCES_SUCCESS'
export const FETCH_BOARD_RESOURCES_FAIL = 'FETCH_BOARD_RESOURCES_FAIL'

export const CREATE_BOARD_RESOURCE = 'CREATE_BOARD_RESOURCE'
export const CREATE_BOARD_RESOURCE_START = 'CREATE_BOARD_RESOURCE_START'
export const CREATE_BOARD_RESOURCE_SUCCESS = 'CREATE_BOARD_RESOURCE_SUCCESS'
export const CREATE_BOARD_RESOURCE_FAIL = 'CREATE_BOARD_RESOURCE_FAIL'

export const DELETE_BOARD_RESOURCE = 'DELETE_BOARD_RESOURCE'
export const DELETE_BOARD_RESOURCE_START = 'DELETE_BOARD_RESOURCE_START'
export const DELETE_BOARD_RESOURCE_SUCCESS = 'DELETE_BOARD_RESOURCE_SUCCESS'
export const DELETE_BOARD_RESOURCE_FAIL = 'DELETE_BOARD_RESOURCE_FAIL'

export const UPDATE_BOARD_RESOURCE = 'UPDATE_BOARD_RESOURCE'
export const UPDATE_BOARD_RESOURCE_START = 'UPDATE_BOARD_RESOURCE_START'
export const UPDATE_BOARD_RESOURCE_SUCCESS = 'UPDATE_BOARD_RESOURCE_SUCCESS'
export const UPDATE_BOARD_RESOURCE_FAIL = 'UPDATE_BOARD_RESOURCE_FAIL'
